name: CI

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    name: PHPUnit

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
      - run: composer install --prefer-dist --no-interaction
      - run: vendor/bin/phpunit tests --color
      - run: vendor/bin/phpcs --standard=PSR12 --colors -n src
      # - run: vendor/bin/phpcs --standard=PSR12 --exclude=PSR1.Methods.CamelCapsMethodName --colors -n src tests
